[project]
# PEP 621 project metadata
# See https://www.python.org/dev/peps/pep-0621/
name = "avilla-workspace"
dependencies = [
    "graia-broadcast>=0.17.5",
    "graia-amnesia>=0.5.2",
    "loguru>=0.6.0",
    "yarl>=1.7.2",
    "launart>=0.6.2",
    "statv>=0.2.2",
    "aiohttp>=3.8.1",
    "creart>=0.2.1",
    "creart-graia>=0.1.5",
    "funcparserlib>=1.0.1",
    "ipykernel>=6.23.2",
    "pip>=23.1.2",
    "ichika>=0.0.8",
]
version = "0"
requires-python = ">=3.9"

[tool.pdm.dev-dependencies]
dev = [
    "black>=22.3.0",
    "flake8>=4.0.1",
    "isort>=5.10.1",
    "typing-extensions>=4.2.0",
    "graia-scheduler>=0.0.8",
    "mina-build>=0.2.6",
    "pre-commit>=2.20.0",
    "devtools>=0.9.0",
    "richuru>=0.1.1",
    "ruff>=0.0.272",
]

[build-system]
requires = ["mina-build"]
build-backend = "mina.backend"

[tool.mina]
enabled = false

[tool.black]
include = '\.pyi?$'
line-length = 120
target-version = ['py39']

[tool.isort]
profile = "black"

[tool.mina.packages.core]
includes = ["avilla/core", "avilla/core/py.typed", "avilla/spec/core"]

[tool.mina.packages.core.project]
name = "avilla-core"
version = "1.0.0-alpha.5"
authors = [
  {name = "GreyElaina", email = "GreyElaina@outlook.com"},
  {name = "BlueGlassBlock", email = "blueglassblock@outlook.com"},
  {name = "ProgramRipper", email = "programripper@foxmail.com"},
  {name = "RF-Tar-Railt", email = "rf_tar_railt@qq.com"}
]
dependencies = [
    "graia-broadcast",
    "graia-amnesia",
    "loguru",
    "yarl",
    "launart"
]
description = ""
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.9"

[tool.mina.packages.core.project.urls]
homepage = "https://github.com/GraiaProject/Avilla"
repository = "https://github.com/GraiaProject/Avilla"

[tool.mina.packages.elizabeth]
includes = ["avilla/elizabeth"]
raw-dependencies = [
  "avilla-core >= 1.0.0-alpha.5",
  "avilla-spec-qq >= 1.0.0-alpha.5"
]

[tool.mina.packages.elizabeth.project]
name = "avilla-elizabeth"
version = "1.0.0-alpha.5" # WIP for release.
authors = [
  {name = "GreyElaina", email = "GreyElaina@outlook.com"},
]
dependencies = []
description = ""
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.9"

[tool.mina.packages.elizabeth.project.urls]
homepage = "https://github.com/GraiaProject/Avilla"
repository = "https://github.com/GraiaProject/Avilla"

[tool.mina.packages."spec/qq"]
includes = ["avilla/spec/qq"]
raw_dependencies = [
  "avilla-core >= 1.0.0-alpha.5",
]

[tool.mina.packages."spec/qq".project]
name = "avilla-spec-qq"
version = "1.0.0-alpha.5"
authors = [
  {name = "GreyElaina", email = "GreyElaina@outlook.com"},
  {name = "BlueGlassBlock", email = "blueglassblock@outlook.com"},
  {name = "ProgramRipper", email = "programripper@foxmail.com"},
  {name = "RF-Tar-Railt", email = "rf_tar_railt@qq.com"}
]
dependencies = []
description = ""
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.9"

[tool.mina.packages."spec/qq".project.urls]
homepage = "https://github.com/GraiaProject/Avilla"
repository = "https://github.com/GraiaProject/Avilla"