[tool.poetry]
name = "avilla-core"
version = "0.0.6"
description = ""
authors = ["GreyElaina <GreyElaina@outlook.com>"]
license = "MiT"
packages = [
    { include = "avilla", from = "src" },
    { include = "avilla/py.typed", from = "src" },
]
readme = 'README.md'

repository = "https://github.com/GraiaProject/AvillaCore"
homepage = "https://github.com/GraiaProject/AvillaCore"


[tool.poetry.dependencies]
python = "^3.8"
graia-broadcast = "^0.12.3"
pydantic = "^1.8.2"
yarl = "^1.6.3"
aiofiles = "^0.7.0"

# Network Support
aiohttp = "^3.7.4"

# Onebot Event Parsing
immutables = "^0.15"

# Tools: Template
regex = { version = "^2021.8.3", optional = true }

[tool.poetry.dev-dependencies]
black = "^21.6b0"
isort = "^5.9.3"
pylint = "^2.9.6"
flake8 = "^3.9.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 100
target-version = ['py38']
include = '\.pyi?$'

[tool.poetry.extras]
template = ['regex']