[tool.poetry]
authors = ["GreyElaina <GreyElaina@outlook.com>"]
description = ""
license = "MIT"
name = "avilla-core"
packages = [
  {include = "avilla/core"},
  {include = "avilla/core/py.typed"},
  {include = "avilla/io"},
]
readme = 'README.md'
version = "0.1.0"

homepage = "https://github.com/GraiaProject/AvillaCore"
repository = "https://github.com/GraiaProject/AvillaCore"

[tool.poetry.dependencies]
graia-broadcast = "^0.15.2"
python = "^3.8"
loguru = "^0.5.3"
pydantic = "^1.9.0"
rich = "^10.13.0"
yarl = "^1.6.3"

aiohttp = {version = "^3.8.1", optional = true}
pyhocon = {version = "^0.3.59", optional = true}
aioredis = {version = "^2.0.0", optional = true}
starlette = {version = "^0.17.1", optional = true}
uvicorn = {version = "^0.16.0", optional = true}

sqlmodel = "^0.0.6"
aiosqlite = {version = "^0.17.0", optional = true}

[tool.poetry.dev-dependencies]
black = "^21.12b0"
flake8 = "^4.0.1"
isort = "^5.10.1"
typing-extensions = "^3.10.0"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[tool.black]
include = '\.pyi?$'
line-length = 110
target-version = ['py38']

[tool.isort]
profile = "black"

[tool.poetry.extras]
aiohttp = ['aiohttp']
aioredis = ['aioredis']
pyhocon = ['pyhocon']
starlette = ['starlette']
uvicorn = ['uvicorn']
aiosqlite = ['aiosqlite']