[tool.poetry]
name = "avilla-core"
version = "0.1.0"
description = ""
authors = ["GreyElaina <GreyElaina@outlook.com>"]
license = "MiT"
packages = [
    { include = "avilla", from = "src" }
]

[tool.poetry.dependencies]
python = "^3.8"
graia-broadcast = "^0.11.3"
pydantic = "^1.8.2"
singledispatch = "^3.6.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
