[tool.poetry]
authors = ["GreyElaina <GreyElaina@outlook.com>"]
description = ""
license = "MIT"
name = "avilla-core"
packages = [
  {include = "avilla/core"},
  {include = "avilla/core/py.typed"},
]
readme = 'README.md'
version = "0.0.15"

homepage = "https://github.com/GraiaProject/AvillaCore"
repository = "https://github.com/GraiaProject/AvillaCore"

[tool.poetry.dependencies]
graia-broadcast = "^0.14.3"
loguru = "^0.5.3"
prompt-toolkit = "^3.0.23"
pydantic = "^1.8.2"
python = "^3.8"
rich = "^10.13.0"
typing-extensions = "^3.10.0"
yarl = "^1.6.3"

# Network Support
aiohttp = "^3.7.4"

# Tools: Template
immutables = "^0.16"
regex = {version = "^2021.8.3", optional = true}

starlette = {version = "^0.17.1", optional = true}
uvicorn = {version = "^0.16.0", optional = true}

[tool.poetry.dev-dependencies]
black = "^21.6b0"
flake8 = "^3.9.2"
isort = "^5.9.3"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[tool.black]
include = '\.pyi?$'
line-length = 110
target-version = ['py38']

[tool.isort]
profile = "black"

[tool.poetry.extras]
starlette = ['starlette']
uvicorn = ['uvicorn']
