[project]
# PEP 621 project metadata
# See https://www.python.org/dev/peps/pep-0621/
name = "avilla-workspace"
dependencies = [
    "graia-broadcast>=0.17.5",
    "graia-amnesia>=0.5.2",
    "loguru>=0.6.0",
    "yarl>=1.7.2",
    "launart>=0.4.2",
    "statv>=0.2.2",
    "aiohttp>=3.8.1",
    "creart>=0.2.1",
    "creart-graia>=0.1.5",
]
version = "0"
requires-python = ">=3.9"
[project.optional-dependencies]

[tool.pdm.dev-dependencies]
dev = [
    "black>=22.3.0",
    "flake8>=4.0.1",
    "isort>=5.10.1",
    "typing-extensions>=4.2.0",
    "graia-scheduler>=0.0.8",
    "pdm-mina>=0.2.0",
    "mina-build>=0.2.6",
    "pre-commit>=2.20.0",
    "devtools>=0.9.0",
]

[build-system]
requires = ["mina-build"]
build-backend = "mina.backend"

[tool.mina]
enabled = false

[tool.black]
include = '\.pyi?$'
line-length = 120
target-version = ['py39']

[tool.isort]
profile = "black"

[tool.mina.packages.core]
includes = ["avilla/core", "avilla/core/py.typed"]

[tool.mina.packages.core.project]
name = "avilla-core"
version = "1.0.0rc3"
authors = [
  {name = "GreyElaina", email = "GreyElaina@outlook.com"},
]
dependencies = [
    "graia-broadcast",
    "graia-amnesia",
    "loguru",
    "yarl",
    "launart"
]
description = ""
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.9"

[tool.mina.packages.core.project.urls]
homepage = "https://github.com/GraiaProject/Avilla"
repository = "https://github.com/GraiaProject/Avilla"

[tool.mina.packages.irc]
includes = ["avilla/irc"]
raw-dependencies = [
  "avilla-core>=1.0.0rc3"
]

[tool.mina.packages.irc.project]
name = "avilla-irc"
version = "1.0.0rc3" # WIP for release.
authors = [
  {name = "GreyElaina", email = "GreyElaina@outlook.com"},
]
dependencies = ["irc"]
description = ""
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.9"

[tool.mina.packages.irc.project.urls]
homepage = "https://github.com/GraiaProject/Avilla"
repository = "https://github.com/GraiaProject/Avilla"
