includes = ["avilla/console"]
raw-dependencies = [
  "avilla-core >= 1.0.0a6",
]

[project]
name = "avilla-console"
version = "1.0.0a9" # WIP for release.
authors = [
  {name = "RF-Tar-Railt", email = "rf_tar_railt@qq.com"},
]
dependencies = [
  "nonechat"
]
description = "Avilla Console Protocol"
license = {text = "AGPL-3.0"}
readme = "README.md"
requires-python = ">=3.9"

[project.urls]
homepage = "https://github.com/GraiaProject/Avilla"
repository = "https://github.com/GraiaProject/Avilla"