includes = ["avilla/red"]
raw_dependencies = [
  "avilla-core >= 1.0.0a8",
  "avilla-standard-qq >= 1.0.0a7",
]

[project]
name = "avilla-red"
version = "1.0.0a9"
authors = [
  {name = "RF-Tar-Railt", email = "rf_tar_railt@qq.com"}
]
dependencies = [
  "aiohttp",
  "selectolax",
]
description = ""
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.9"

[project.urls]
homepage = "https://github.com/GraiaProject/Avilla"
repository = "https://github.com/GraiaProject/Avilla"