includes = ["avilla/standard/qq"]
raw_dependencies = [
  "avilla-core >= 1.0.0a8",
]

[project]
name = "avilla-standard-qq"
version = "1.0.0a9"
authors = [
  {name = "GreyElaina", email = "GreyElaina@outlook.com"},
  {name = "BlueGlassBlock", email = "blueglassblock@outlook.com"},
  {name = "ProgramRipper", email = "programripper@foxmail.com"},
  {name = "RF-Tar-Railt", email = "rf_tar_railt@qq.com"}
]
dependencies = []
description = ""
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.9"

[project.urls]
homepage = "https://github.com/GraiaProject/Avilla"
repository = "https://github.com/GraiaProject/Avilla"