includes = ["avilla/telegram"]
raw-dependencies = [
  "avilla-core >= 1.0.0a8",
]

[project]
name = "avilla-telegram"
version = "0.1.0" # WIP for release.
authors = [
  {name = "nullqwertyuiop", email = "null@member.fsf.org"},
]
dependencies = [
  "python-telegram-bot"
]
description = "Avilla Telegram Protocol"
license = {text = "GPL-3.0"}
readme = "README.md"
requires-python = ">=3.9"

[project.urls]
homepage = "https://github.com/GraiaProject/Avilla"
repository = "https://github.com/GraiaProject/Avilla"