includes = ["avilla/twilight"]
raw-dependencies = [
  "avilla-core >= 1.0.0-alpha.8",
  "pydantic >= 1.10.0",
]

[project]
name = "avilla-twilight"
version = "0.2.0" # WIP for release.
authors = [
  {name = "GreyElaina", email = "GreyElaina@outlook.com"},
  {name = "BlueGlassBlock", email = "blueglassblock@outlook.com"},
  {name = "ProgramRipper", email = "programripper@foxmail.com"},
  {name = "RF-Tar-Railt", email = "rf_tar_railt@qq.com"}
]
dependencies = []
description = "Twilight Message Parser for Avilla"
license = {text = "AGPL-3.0"}
requires-python = ">=3.9"

[project.urls]
homepage = "https://github.com/GraiaProject/Avilla"
repository = "https://github.com/GraiaProject/Avilla"