name: "Misc: Move Secrets"
on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Secrets Sync Action
        uses: jpoehnelt/secrets-sync-action@v1.8.0
        with:
          secrets: |
            PYPI_TOKEN
          repositories: |
            GreyElaina/Ryanvk
          dry_run: true
          github_token: ${{ secrets.GREYELAINA_TEMP_TOKEN }}
      
