name: Python package
on:
  push:
    tags:
      - "console-*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        name: Ensure Python Runtime
        with:
          python-version: "3.x"
          architecture: "x64"
      - name: Ensure PDM & twine
        run: |
          python3 -m pip install pdm twine pdm-mina mina-build
      - name: Build Package
        run: |
          pdm mina build console
      - name: Publish to PyPI
        run: |
          twine upload dist/* --non-interactive -u __token__ -p ${{ secrets.PYPI_TOKEN }}
