name: "PyPI Publish: Twilight"
on:
  workflow_dispatch: {}
  push:
    tags:
      - "twilight-v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        name: Ensure Python Runtime
        with:
          python-version: "3.x"
          architecture: "x64"
      - name: Ensure PDM & twine
        run: |
          python3 -m pip install pdm twine pdm-mina "mina-build<0.6"
      - name: Build Package
        run: |
          export MINA_BUILD_TARGET=twilight && pdm mina build twilight
      - name: Publish to PyPI
        run: |
          twine upload dist/* --non-interactive -u __token__ -p ${{ secrets.PYPI_TOKEN }}
