name: "PyPI Publish: Core"
on:
  workflow_dispatch: {}
  push:
    tags:
      - "core-v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        name: Ensure Python Runtime
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Ensure PDM & twine
        run: |
          python3 -m pip install pdm twine pdm-mina "mina-build<0.6"
      - name: Build Package
        run: |
          export MINA_BUILD_TARGET=core && pdm mina build core --no-isolation
      - name: Publish to PyPI
        run: |
          twine upload dist/* --non-interactive -u __token__ -p ${{ secrets.PYPI_TOKEN }}